### PR TITLE
added nbm-maven and mojo-archetypes

### PR DESCRIPTION
**Pull request by mkleint**
there's multiple tags prefixes for both nbm-maven and mojo-archetypes, I just picked one, wasn't sure there's a way to add more there..

### CODE REVIEW

**Comment by batmat** [comment]
Indeed, I don't think there's a way currently. We'll have to rework the script or do that manually.

**Comment by mkleint** [comment]
personally I don't really care, if they get preserved. the nbm-maven-plugin ones are the only ones important anyway..

**Comment by batmat** [comment]
Well, if they're all under tags, that should be pretty easy. I already did it for branches (only findbugs-m-p used it): separating branches with pipes (|).

What the other tag format so that I can test it out?

Thanks

**Comment by batmat** [comment]
To be clearer, I think I could add support for something like :

```
nbm-maven,trunk/mojo/nbm-maven,nbm-maven-|the-other-beginning|and-so-on,
```

Thanks

**Comment by mkleint** [comment]
now that I think of it.. I'm wondering if multiple tags or multiple lines are the way to go.. eg.

nbm-maven-plugin,trunk/mojo/nbm-maven/nbm-maven-plugin,nbm-maven-plugin-,
nb-repository-plugin,trunk/mojo/nbm-maven/nb-repository-plugin,nb-repository-plugin-,

**Comment by batmat** [comment]
As you wish. You're more apt than to judge what do you with those precise
plugins :-)

2015-05-18 4:29 GMT+02:00 Milos Kleint notifications@github.com:

> now that I think of it.. I'm wondering if multiple tags or multiple lines
> are the way to go.. eg.
> 
> nbm-maven-plugin,trunk/mojo/nbm-maven/nbm-maven-plugin,nbm-maven-plugin-,
> 
> nb-repository-plugin,trunk/mojo/nbm-maven/nb-repository-plugin,nb-repository-plugin-,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/convert-to-git/pull/26#issuecomment-102897575
> .

## 

Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by mkleint** [comment]
Ok, here's the updated PR with one entry per project in nbm-maven/ and mojo-archetypes/ directories, I've omitted the parent/aggregator projects, I believe there's little need for them now that stuff is in separate git repos.

**Pull request merged**
